version: 2
references:
  workspace: &workspace
    ~/workspace
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-27-alpha
    environment:
      TERM: dumb
      _JAVA_OPTIONS: "-Xmx2048m -XX:+UnlockExperimentalVMOptions -XX:+UseCGroupMemoryLimitForHeap"
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx2048m"'

jobs:
  build:
    <<: *android_config
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}-{{ checksum  "rxlifecycleowner/build.gradle" }}-{{ checksum  "rxlifecycleowner-viewmodel/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "sample/build.gradle" }}-{{ checksum  "rxlifecycleowner/build.gradle" }}-{{ checksum  "rxlifecycleowner-viewmodel/build.gradle" }}
      - run:
          name: Build
          command: ./gradlew test

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
